# =====================
# GENERAL
# =====================
set -g mouse on
set -g base-index 1
set -g xterm-keys on
set -sg escape-time 0
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*:Tc"
# =====================
# RELOAD CONFIG
# =====================
bind r source-file ~/.psmux.conf \; display-message "Reloaded!"
# =====================
# SPLITS
# =====================
bind | split-window -h
bind - split-window -v
# =====================
# RESIZE (stable Windows Terminal-safe)
# =====================
bind -n C-M-h resize-pane -L 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-l resize-pane -R 5
# =====================
# LAYOUT
# =====================
bind = select-layout even-horizontal

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R
